
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
#      securityContext:
#        fsGroup: 1000820000
#        fsGroupChangePolicy: "Always"
#        runAsNonRoot: true
#        seccompProfile:
#          type: RuntimeDefault
      containers:
        - name: postgres
          image: postgres:15 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
#          securityContext:
#            fsGroup: 1000820000
#            fsGroupChangePolicy: "Always"
#            allowPrivilegeEscalation: false
#            capabilities:
#              drop: [ALL]
#              runAsNonRoot: true
      volumes:
        - name: postgresdb
          emptyDir:
            sizeLimit: 5Gi

